### ISSUE TITLE
FEATURE: 計算MFE和MAE

### ISSUE THREAD

**Issue by RainBoltz** [RainBoltz/pymfae#1]
計算各個trade在持有時的mfe和mae，並繪製出 win-trade v.s lose-trade的 MFE/MAE 二維座標圖

**Comment by fatfingererr** [comment]
Great ! 我都有在 follow , 你看你時間都 ok ~ 不急~

**Comment by RainBoltz** [comment]
- [x] 計算坊間 MFE

- [x] 計算 MAE
- [x] 計算 Ricky式的 MFE


- [x] 若選擇批次輸出，則return一個list：
```
[
    (mae, mfe),
    ...
]
```

決定重新製作套件 (配合影片?)，順便練開源專案手感XD

**Comment by fatfingererr** [comment]
GOGO! 我覺得至少做完可以包裝一下, 我相信應該可以被很多人用, python 應該也還沒有套件
python 我就 pass 惹 XD 我可以幫忙美化 README 和 Docs
